language: php

php:
  - 7.0
  - nightly

env:
  - # default environment without variables
  - COMPOSER_DEPENDENCIES_OPTIONS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update

script:
  - composer update --no-interaction --prefer-source $COMPOSER_DEPENDENCIES_OPTIONS
  - vendor/bin/phing

after_script:
  - php vendor/bin/coveralls -v
