<?php declare(strict_types=1);

namespace SlevomatCsobGateway;

use function array_search;

class Country
{
    public const AFG = 'AF';
    public const ALA = 'AX';
    public const ALB = 'AL';
    public const DZA = 'DZ';
    public const ASM = 'AS';
    public const AND = 'AD';
    public const AGO = 'AO';
    public const AIA = 'AI';
    public const ATA = 'AQ';
    public const ATG = 'AG';
    public const ARG = 'AR';
    public const ARM = 'AM';
    public const ABW = 'AW';
    public const AUS = 'AU';
    public const AUT = 'AT';
    public const AZE = 'AZ';
    public const BHS = 'BS';
    public const BHR = 'BH';
    public const BGD = 'BD';
    public const BRB = 'BB';
    public const BLR = 'BY';
    public const BEL = 'BE';
    public const BLZ = 'BZ';
    public const BEN = 'BJ';
    public const BMU = 'BM';
    public const BTN = 'BT';
    public const BOL = 'BO';
    public const BIH = 'BA';
    public const BES = 'BQ';
    public const BWA = 'BW';
    public const BVT = 'BV';
    public const BRA = 'BR';
    public const IOT = 'IO';
    public const BRN = 'BN';
    public const BGR = 'BG';
    public const BFA = 'BF';
    public const BDI = 'BI';
    public const KHM = 'KH';
    public const CMR = 'CM';
    public const CAN = 'CA';
    public const CPV = 'CV';
    public const CYM = 'KY';
    public const CAF = 'CF';
    public const TCD = 'TD';
    public const CHL = 'CL';
    public const CHN = 'CN';
    public const CXR = 'CX';
    public const CCK = 'CC';
    public const COL = 'CO';
    public const COM = 'KM';
    public const COG = 'CG';
    public const COK = 'CK';
    public const CRI = 'CR';
    public const CIV = 'CI';
    public const HRV = 'HR';
    public const CUB = 'CU';
    public const CUW = 'CW';
    public const CYP = 'CY';
    public const CZE = 'CZ';
    public const COD = 'CD';
    public const DNK = 'DK';
    public const DJI = 'DJ';
    public const DMA = 'DM';
    public const DOM = 'DO';
    public const ECU = 'EC';
    public const EGY = 'EG';
    public const SLV = 'SV';
    public const GNQ = 'GQ';
    public const ERI = 'ER';
    public const EST = 'EE';
    public const ETH = 'ET';
    public const FLK = 'FK';
    public const FRO = 'FO';
    public const FJI = 'FJ';
    public const FIN = 'FI';
    public const FRA = 'FR';
    public const GUF = 'GF';
    public const PYF = 'PF';
    public const ATF = 'TF';
    public const GAB = 'GA';
    public const GMB = 'GM';
    public const GEO = 'GE';
    public const DEU = 'DE';
    public const GHA = 'GH';
    public const GIB = 'GI';
    public const GRC = 'GR';
    public const GRL = 'GL';
    public const GRD = 'GD';
    public const GLP = 'GP';
    public const GUM = 'GU';
    public const GTM = 'GT';
    public const GGY = 'GG';
    public const GIN = 'GN';
    public const GNB = 'GW';
    public const GUY = 'GY';
    public const HTI = 'HT';
    public const HMD = 'HM';
    public const HND = 'HN';
    public const HKG = 'HK';
    public const HUN = 'HU';
    public const ISL = 'IS';
    public const IND = 'IN';
    public const IDN = 'ID';
    public const IRQ = 'IQ';
    public const IRL = 'IE';
    public const IRN = 'IR';
    public const IMN = 'IM';
    public const ISR = 'IL';
    public const ITA = 'IT';
    public const JAM = 'JM';
    public const JPN = 'JP';
    public const JEY = 'JE';
    public const JOR = 'JO';
    public const KAZ = 'KZ';
    public const KEN = 'KE';
    public const KIR = 'KI';
    public const XKX = 'XK';
    public const KWT = 'KW';
    public const KGZ = 'KG';
    public const LAO = 'LA';
    public const LVA = 'LV';
    public const LBN = 'LB';
    public const LSO = 'LS';
    public const LBR = 'LR';
    public const LBY = 'LY';
    public const LIE = 'LI';
    public const LTU = 'LT';
    public const LUX = 'LU';
    public const MAC = 'MO';
    public const MKD = 'MK';
    public const MDG = 'MG';
    public const MWI = 'MW';
    public const MYS = 'MY';
    public const MDV = 'MV';
    public const MLI = 'ML';
    public const MLT = 'MT';
    public const MHL = 'MH';
    public const MTQ = 'MQ';
    public const MRT = 'MR';
    public const MUS = 'MU';
    public const MYT = 'YT';
    public const MEX = 'MX';
    public const FSM = 'FM';
    public const MDA = 'MD';
    public const MCO = 'MC';
    public const MNG = 'MN';
    public const MNE = 'ME';
    public const MSR = 'MS';
    public const MAR = 'MA';
    public const MOZ = 'MZ';
    public const MMR = 'MM';
    public const NAM = 'NA';
    public const NRU = 'NR';
    public const NPL = 'NP';
    public const NLD = 'NL';
    public const NCL = 'NC';
    public const NZL = 'NZ';
    public const NIC = 'NI';
    public const NER = 'NE';
    public const NGA = 'NG';
    public const NIU = 'NU';
    public const NFK = 'NF';
    public const MNP = 'MP';
    public const PRK = 'KP';
    public const NOR = 'NO';
    public const OMN = 'OM';
    public const PAK = 'PK';
    public const PLW = 'PW';
    public const PSE = 'PS';
    public const PAN = 'PA';
    public const PNG = 'PG';
    public const PRY = 'PY';
    public const PER = 'PE';
    public const PHL = 'PH';
    public const PCN = 'PN';
    public const POL = 'PL';
    public const PRT = 'PT';
    public const PRI = 'PR';
    public const QAT = 'QA';
    public const REU = 'RE';
    public const ROU = 'RO';
    public const RUS = 'RU';
    public const RWA = 'RW';
    public const SHN = 'SH';
    public const KNA = 'KN';
    public const LCA = 'LC';
    public const SXM = 'SX';
    public const MAF = 'MF';
    public const SPM = 'PM';
    public const VCT = 'VC';
    public const WSM = 'WS';
    public const SMR = 'SM';
    public const STP = 'ST';
    public const SAU = 'SA';
    public const SEN = 'SN';
    public const SRB = 'RS';
    public const SYC = 'SC';
    public const SLE = 'SL';
    public const SGP = 'SG';
    public const SVK = 'SK';
    public const SVN = 'SI';
    public const SLB = 'SB';
    public const SOM = 'SO';
    public const ZAF = 'ZA';
    public const SGS = 'GS';
    public const KOR = 'KR';
    public const SSU = 'SS';
    public const ESP = 'ES';
    public const LKA = 'LK';
    public const SDN = 'SD';
    public const SUR = 'SR';
    public const SJM = 'SJ';
    public const SWZ = 'SZ';
    public const SWE = 'SE';
    public const CHE = 'CH';
    public const SYR = 'SY';
    public const TWN = 'TW';
    public const TJK = 'TJ';
    public const TZA = 'TZ';
    public const THA = 'TH';
    public const TLS = 'TL';
    public const TGO = 'TG';
    public const TKL = 'TK';
    public const TON = 'TO';
    public const TTO = 'TT';
    public const TUN = 'TN';
    public const TUR = 'TR';
    public const TKM = 'TM';
    public const TCA = 'TC';
    public const TUV = 'TV';
    public const UGA = 'UG';
    public const UKR = 'UA';
    public const ARE = 'AE';
    public const GBR = 'GB';
    public const USA = 'US';
    public const UMI = 'UM';
    public const URY = 'UY';
    public const UZB = 'UZ';
    public const VUT = 'VU';
    public const VAT = 'VA';
    public const VEN = 'VE';
    public const VNM = 'VN';
    public const VGB = 'VG';
    public const VIR = 'VI';
    public const WLF = 'WF';
    public const ESH = 'EH';
    public const YEM = 'YE';
    public const ZMB = 'ZM';
    public const ZWE = 'ZW';
    private const LONG_CODES = [
        'AFG' => self::AFG,
        'ALA' => self::ALA,
        'ALB' => self::ALB,
        'DZA' => self::DZA,
        'ASM' => self::ASM,
        'AND' => self::AND,
        'AGO' => self::AGO,
        'AIA' => self::AIA,
        'ATA' => self::ATA,
        'ATG' => self::ATG,
        'ARG' => self::ARG,
        'ARM' => self::ARM,
        'ABW' => self::ABW,
        'AUS' => self::AUS,
        'AUT' => self::AUT,
        'AZE' => self::AZE,
        'BHS' => self::BHS,
        'BHR' => self::BHR,
        'BGD' => self::BGD,
        'BRB' => self::BRB,
        'BLR' => self::BLR,
        'BEL' => self::BEL,
        'BLZ' => self::BLZ,
        'BEN' => self::BEN,
        'BMU' => self::BMU,
        'BTN' => self::BTN,
        'BOL' => self::BOL,
        'BIH' => self::BIH,
        'BES' => self::BES,
        'BWA' => self::BWA,
        'BVT' => self::BVT,
        'BRA' => self::BRA,
        'IOT' => self::IOT,
        'BRN' => self::BRN,
        'BGR' => self::BGR,
        'BFA' => self::BFA,
        'BDI' => self::BDI,
        'KHM' => self::KHM,
        'CMR' => self::CMR,
        'CAN' => self::CAN,
        'CPV' => self::CPV,
        'CYM' => self::CYM,
        'CAF' => self::CAF,
        'TCD' => self::TCD,
        'CHL' => self::CHL,
        'CHN' => self::CHN,
        'CXR' => self::CXR,
        'CCK' => self::CCK,
        'COL' => self::COL,
        'COM' => self::COM,
        'COG' => self::COG,
        'COK' => self::COK,
        'CRI' => self::CRI,
        'CIV' => self::CIV,
        'HRV' => self::HRV,
        'CUB' => self::CUB,
        'CUW' => self::CUW,
        'CYP' => self::CYP,
        'CZE' => self::CZE,
        'COD' => self::COD,
        'DNK' => self::DNK,
        'DJI' => self::DJI,
        'DMA' => self::DMA,
        'DOM' => self::DOM,
        'ECU' => self::ECU,
        'EGY' => self::EGY,
        'SLV' => self::SLV,
        'GNQ' => self::GNQ,
        'ERI' => self::ERI,
        'EST' => self::EST,
        'ETH' => self::ETH,
        'FLK' => self::FLK,
        'FRO' => self::FRO,
        'FJI' => self::FJI,
        'FIN' => self::FIN,
        'FRA' => self::FRA,
        'GUF' => self::GUF,
        'PYF' => self::PYF,
        'ATF' => self::ATF,
        'GAB' => self::GAB,
        'GMB' => self::GMB,
        'GEO' => self::GEO,
        'DEU' => self::DEU,
        'GHA' => self::GHA,
        'GIB' => self::GIB,
        'GRC' => self::GRC,
        'GRL' => self::GRL,
        'GRD' => self::GRD,
        'GLP' => self::GLP,
        'GUM' => self::GUM,
        'GTM' => self::GTM,
        'GGY' => self::GGY,
        'GIN' => self::GIN,
        'GNB' => self::GNB,
        'GUY' => self::GUY,
        'HTI' => self::HTI,
        'HMD' => self::HMD,
        'HND' => self::HND,
        'HKG' => self::HKG,
        'HUN' => self::HUN,
        'ISL' => self::ISL,
        'IND' => self::IND,
        'IDN' => self::IDN,
        'IRQ' => self::IRQ,
        'IRL' => self::IRL,
        'IRN' => self::IRN,
        'IMN' => self::IMN,
        'ISR' => self::ISR,
        'ITA' => self::ITA,
        'JAM' => self::JAM,
        'JPN' => self::JPN,
        'JEY' => self::JEY,
        'JOR' => self::JOR,
        'KAZ' => self::KAZ,
        'KEN' => self::KEN,
        'KIR' => self::KIR,
        'XKX' => self::XKX,
        'KWT' => self::KWT,
        'KGZ' => self::KGZ,
        'LAO' => self::LAO,
        'LVA' => self::LVA,
        'LBN' => self::LBN,
        'LSO' => self::LSO,
        'LBR' => self::LBR,
        'LBY' => self::LBY,
        'LIE' => self::LIE,
        'LTU' => self::LTU,
        'LUX' => self::LUX,
        'MAC' => self::MAC,
        'MKD' => self::MKD,
        'MDG' => self::MDG,
        'MWI' => self::MWI,
        'MYS' => self::MYS,
        'MDV' => self::MDV,
        'MLI' => self::MLI,
        'MLT' => self::MLT,
        'MHL' => self::MHL,
        'MTQ' => self::MTQ,
        'MRT' => self::MRT,
        'MUS' => self::MUS,
        'MYT' => self::MYT,
        'MEX' => self::MEX,
        'FSM' => self::FSM,
        'MDA' => self::MDA,
        'MCO' => self::MCO,
        'MNG' => self::MNG,
        'MNE' => self::MNE,
        'MSR' => self::MSR,
        'MAR' => self::MAR,
        'MOZ' => self::MOZ,
        'MMR' => self::MMR,
        'NAM' => self::NAM,
        'NRU' => self::NRU,
        'NPL' => self::NPL,
        'NLD' => self::NLD,
        'NCL' => self::NCL,
        'NZL' => self::NZL,
        'NIC' => self::NIC,
        'NER' => self::NER,
        'NGA' => self::NGA,
        'NIU' => self::NIU,
        'NFK' => self::NFK,
        'MNP' => self::MNP,
        'PRK' => self::PRK,
        'NOR' => self::NOR,
        'OMN' => self::OMN,
        'PAK' => self::PAK,
        'PLW' => self::PLW,
        'PSE' => self::PSE,
        'PAN' => self::PAN,
        'PNG' => self::PNG,
        'PRY' => self::PRY,
        'PER' => self::PER,
        'PHL' => self::PHL,
        'PCN' => self::PCN,
        'POL' => self::POL,
        'PRT' => self::PRT,
        'PRI' => self::PRI,
        'QAT' => self::QAT,
        'REU' => self::REU,
        'ROU' => self::ROU,
        'RUS' => self::RUS,
        'RWA' => self::RWA,
        'SHN' => self::SHN,
        'KNA' => self::KNA,
        'LCA' => self::LCA,
        'SXM' => self::SXM,
        'MAF' => self::MAF,
        'SPM' => self::SPM,
        'VCT' => self::VCT,
        'WSM' => self::WSM,
        'SMR' => self::SMR,
        'STP' => self::STP,
        'SAU' => self::SAU,
        'SEN' => self::SEN,
        'SRB' => self::SRB,
        'SYC' => self::SYC,
        'SLE' => self::SLE,
        'SGP' => self::SGP,
        'SVK' => self::SVK,
        'SVN' => self::SVN,
        'SLB' => self::SLB,
        'SOM' => self::SOM,
        'ZAF' => self::ZAF,
        'SGS' => self::SGS,
        'KOR' => self::KOR,
        'SSU' => self::SSU,
        'ESP' => self::ESP,
        'LKA' => self::LKA,
        'SDN' => self::SDN,
        'SUR' => self::SUR,
        'SJM' => self::SJM,
        'SWZ' => self::SWZ,
        'SWE' => self::SWE,
        'CHE' => self::CHE,
        'SYR' => self::SYR,
        'TWN' => self::TWN,
        'TJK' => self::TJK,
        'TZA' => self::TZA,
        'THA' => self::THA,
        'TLS' => self::TLS,
        'TGO' => self::TGO,
        'TKL' => self::TKL,
        'TON' => self::TON,
        'TTO' => self::TTO,
        'TUN' => self::TUN,
        'TUR' => self::TUR,
        'TKM' => self::TKM,
        'TCA' => self::TCA,
        'TUV' => self::TUV,
        'UGA' => self::UGA,
        'UKR' => self::UKR,
        'ARE' => self::ARE,
        'GBR' => self::GBR,
        'USA' => self::USA,
        'UMI' => self::UMI,
        'URY' => self::URY,
        'UZB' => self::UZB,
        'VUT' => self::VUT,
        'VAT' => self::VAT,
        'VEN' => self::VEN,
        'VNM' => self::VNM,
        'VGB' => self::VGB,
        'VIR' => self::VIR,
        'WLF' => self::WLF,
        'ESH' => self::ESH,
        'YEM' => self::YEM,
        'ZMB' => self::ZMB,
        'ZWE' => self::ZWE,
    ];

    public static function getLongCode(string $shortCode): string
    {
        /** @var string */
        return array_search($shortCode, self::LONG_CODES, true);
    }
}
